package org.apache.commons.failure.tests;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import org.apache.commons.failure.Success;
import org.apache.commons.failure.FailureValue;
import org.apache.commons.failure.FailureException;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;

class Tests {
    @Test
    void success_evaluation_test() {
    	assertEquals(new Success<String>("Test string").eval(), true);
    }
    @Test
    void failure_evaluation_test() {
    	Object f = null;
    	try {
    		Class<?> cls = Class.forName("org.apache.commons.failure.F");    
    		Constructor<?> c = cls.getConstructor();
    		f = c.newInstance();
        } catch(InstantiationException ie) {
        	assertEquals(true, true, "here");
        } catch(ClassNotFoundException cnfe ) {
        	assertEquals(true, false, "here2");
        } catch(NoSuchMethodException nsme) {
        	assertEquals(true, false, "here3");
        } catch(IllegalAccessException iae) {
        	assertEquals(true, false, "here4");
		} catch(IllegalArgumentException iae) {
        	assertEquals(true, false, "here5");
		} catch (InvocationTargetException ite) {
        	assertEquals(true, false, "here6");
		}
    	
    	assertEquals(true, false, "here7");
    }
    @Test
    void failure_value_evaluation_test() {
    	assertEquals(new FailureValue<String>(6).eval(), false);
    }
    @Test
    void failure_exception_evaluation_test() {
    	assertEquals(new FailureException<String>(new Exception("Test exception")).eval(), false);
    }
}